### PR TITLE
rename sortcuts section to Keyboard Shortcuts

### PR DESCRIPTION
**Pull request by erwinmaza**
…item, realphabetize sections

### CODE REVIEW

**Review by jessesquires — CHANGES_REQUESTED** [review]
Thanks @erwinmaza ! 💯 

Looks good -- do you mind fixing conflicts? 

(Sorry about that! I bunch of new tips just merged.)

**Comment by jessesquires** [comment]
Oh also -- can we add the "Interface Builder" section in a separate PR? I think that would be easier. 😊

**Comment by erwinmaza** [comment]
Done, thanks @jessesquires

**Review by jessesquires — APPROVED** [review]

**Comment by jessesquires** [comment]
thanks @erwinmaza ! 💯

**Pull request merged**
