### PR TITLE
Replace all Apple glyph names with their HTML code

### PR DESCRIPTION
**Pull request by codedbypm**
In this PR:

- added a keyboard shortcut for fix-its hint
- replace all Cmd/Alt/Ctrl/Shift/etc with apple glyphs ⌘ ⌥ ⌃ ⇧ etc..

### CODE REVIEW

**Comment by codedbypm** [comment]
I haven't found a way to have glyphs shown between backticks so I decided to bold them all. Let me know what you all think.

**Comment by jessesquires** [comment]
Thanks @codedbypm ! 🎉 💯  I think this looks great.

The only thing is that the section "Quick reference for Apple glyphs HTML codes" is very prominent, a feels a bit awkward.

What if we put that at the very bottom of the page, or in its own page?

**Comment by codedbypm** [comment]
> Thanks @codedbypm ! 🎉 💯 I think this looks great.
> 
> The only thing is that the section "Quick reference for Apple glyphs HTML codes" is very prominent, a feels a bit awkward.
> 
> What if we put that at the very bottom of the page, or in its own page?
> 
> **EDIT:** Oh actually, what about putting the HTML code cheat sheet in the contributing guide?
> https://github.com/Xcode-Tips/xcode-tips.github.io/blob/main/.github/CONTRIBUTING.md

I share your same opinion about that reference. 
My assumption is this: PRs containing the symbol names `cmd` or `shift` etc.. should not be accepted unless they use the glyphs. This is for the sake of having a consistent document. 
If you share my same assumption, then we need the reference somewhere to ease the job to contributors. 
I initially put it at the very top of the README.md but in a comment block, thus visible only if you edit the file :D 
But let me know. I'm fine to put it at the bottom too or on another page. I don't have a big preference here.

**Comment by jessesquires** [comment]
> PRs containing the symbol names cmd or shift etc.. should not be accepted unless they use the glyphs. This is for the sake of having a consistent document.

totally agree!

>  I like the idea of putting it in the CONTRIBUTING.md

Let's go with this!

Let's also add a note to the steps: "Please use Apple Glyphs when mentioning keyboard shortcuts." 😊

**Comment by codedbypm** [comment]
Please review

**Review by jessesquires — APPROVED** [review]
Thanks @codedbypm ! 💯

**Pull request merged**
