### PR TITLE
Use Apple glyphs for Cmd, Alt, Ctrl and Shift

### PR DESCRIPTION
**Pull request by codedbypm**
In this PR:

- added keyboard shortcut for fix-its hint
- replace all Cmd/Alt/Ctrl/Shift with apple glyphs ⌘ ⌥ ⌃ ⇧

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @codedbypm ! 💯 🎉 

I definitely like this idea. 

Some concerns:

1. readability / accessibility. some of the glyphs (especially shift) seem quite small and difficult to read -- at least in the markdown. Maybe the rendered site will be different?
2. We should probably use the html codes for these, right? For example, `&#8984;` which renders as &#8984;

Maybe we use a hybrid approach, like this:

> &#8984;J (cmd-J)

**Review by jessesquires — CHANGES_REQUESTED** [review]
going to formally "request changes" as we discuss 😊

**Comment by codedbypm** [comment]
> Thanks @codedbypm ! 💯 🎉
> 
> I definitely like this idea.
> 
> Some concerns:
> 
> 1. readability / accessibility. some of the glyphs (especially shift) seem quite small and difficult to read -- at least in the markdown. Maybe the rendered site will be different?

Correct. I also noticed that when editing the markdown, they are all a tad small, and shift is the one where the issue is more evident. Here you can see the rendered page. They are visually better than in the raw markdown

image
 
> 2. We should probably use the HTML codes for these, right? For example, `&#8984;` which renders as ⌘

Yeah, HTML feels more future proof. It renders always properly (but not when text is in between backticks!) and allows for easier copy-paste or search-replace operations. For that, I would propose to add a commented-out legend at the beginning of the file to use as a quick reference for the random github user that passes by and wants to contribute and needs those glyphs. 
I'll update the PR and await for your feedback. 

> Maybe we use a hybrid approach, like this:
> 
> > ⌘J (cmd-J)

not sure about the hybrid. What advantages would bring to also have the `(cmd-J)` bit?

**Comment by jessesquires** [comment]
> It renders always properly (but not when text is in between backticks!) 

lol, oops I forgot about that. 😊 

> I'll update the PR and await for your feedback.

Sounds good. And I'm sorry about the conflicts! 😄

**Comment by codedbypm** [comment]
> > It renders always properly (but not when text is in between backticks!)
> 
> lol, oops I forgot about that. 😊
> 
> > I'll update the PR and await for your feedback.
> 
> Sounds good. And I'm sorry about the conflicts! 😄
> 
> Edit: Oh one other thing, it looks like putting a space between characters also helps with readability.
> 
> For example: **⌘ J** vs **⌘J**



> > It renders always properly (but not when text is in between backticks!)
> 
> lol, oops I forgot about that. 😊
> 
> > I'll update the PR and await for your feedback.
> 
> Sounds good. And I'm sorry about the conflicts! 😄
> 
> Edit: Oh one other thing, it looks like putting a space between characters also helps with readability.
> 
> For example: **⌘ J** vs **⌘J**

I updated the PR

**Comment by codedbypm** [comment]
Has content been moved around recently? This PR has now merge conflicts that are not fixable by just one tap. And after spending the whole day, coding, reviewing, fixing conflicts, the last thing I want is to have more conflicts for such a simple repo.

**Comment by jessesquires** [comment]
> Has content been moved around recently? 

Yes. We renamed "Shortcuts" to "Keyboard Shortcuts" and re-alphabetized the list.

> This PR has now merge conflicts that are not fixable by just one tap. And after spending the whole day at work, coding, reviewing, fixing conflicts, etc, the last thing I want in the eve is to have more conflicts to solve

Totally understandable. 🤗 That's why we call it open sores software. 😆 

It might be easier to just re-branch off off `main`. However, it you do not feel up for doing more work here, I totally understand.

**Comment by jessesquires** [comment]
@codedbypm I sent you an invite to join the org, which means you won't have to work off of a fork anymore, and should make development easier.

In the case that you do not want to move forward, I've opened #19 to track this so that someone else could carry this forward if they wish.

Again -- sorry about the conflicts! I know it's frustrating.

**Comment by codedbypm** [comment]
> @codedbypm I sent you an invite to join the org, which means you won't have to work off of a fork anymore, and should make development easier.
> 
> In the case that you do not want to move forward, I've opened #19 to track this so that someone else could carry this forward if they wish.
> 
> Again -- sorry about the conflicts! I know it's frustrating.

No worries. That night was the end of a very long coding day :D My complaint had only the goal to make things better and smoother for whoever comes next. 
I accepted your invite (thx btw) and will send soon a new PR based on the current main. It will be faster than fixing conflicts :D

**Comment by codedbypm** [comment]
Closing this in favor of #20

**Comment by jessesquires** [comment]
> My complaint had only the goal to make things better and smoother for whoever comes next.

I think #16 could help with this. 😊

**Pull request closed without merging**
